-- DROP SCHEMA conferati CASCADE;

create schema if not exists "conferati";

DROP TABLE IF EXISTS "conferati"."person" CASCADE;
DROP TABLE IF EXISTS "conferati"."organization"  CASCADE;
DROP TABLE IF EXISTS "conferati"."organization_role" CASCADE;
DROP TABLE IF EXISTS "conferati"."filtertypes_st" CASCADE;


create table "conferati"."filtertypes_st" (
    "id" bigint generated by default as identity not null,
    "type" text PRIMARY KEY ,
    "created_at" timestamp with time zone default now()
);


CREATE table IF NOT EXISTS "conferati"."organization_role" (
    "id" bigint PRIMARY KEY generated by default as identity,
    "person" bigint not null,
    "organization" bigint not null,
    "title" text not null,
    "start_date" date,
    "end_date" date,
    "created_at" timestamp without time zone not null default now()
);


CREATE table IF NOT EXISTS "conferati"."organization" (
    "id" bigint PRIMARY KEY generated by default as identity,
    "name" text not null,
    "type" text not null REFERENCES conferati.filtertypes_st(type),
    "created_at" timestamp without time zone not null default now()
);


CREATE table IF NOT EXISTS "conferati"."person" (
    "id" bigint PRIMARY KEY generated by default as identity,
    "first_name" text not null,
    "last_name" text not null,
    "birthdate" date,
    "wikipedia_page" text,
    "local_image_url" text,
    "created_at" timestamp without time zone not null default now()
);





-- set check_function_bodies = off;


