alter table "filters"."app_whitefilter_st" drop constraint "app_whitefilter_st_filter_fkey";

alter table "filters"."record_section_blackfilter_st" drop constraint "record_section_blackfilter_st_filter_fkey";

alter table "filters"."record_section_whitefilter_st" drop constraint "record_section_whitefilter_st_filter_fkey";

alter table "filters"."app_whitefilter_st" drop column "filter";

alter table "filters"."app_whitefilter_st" add column "filter_type" text not null;

alter table "filters"."record_section_blackfilter_st" drop column "filter";

alter table "filters"."record_section_blackfilter_st" add column "filter_type" text not null;

alter table "filters"."record_section_whitefilter_st" drop column "filter";

alter table "filters"."record_section_whitefilter_st" add column "filter_type" text not null;

alter table "filters"."app_whitefilter_st" add constraint "app_whitefilter_st_filter_type_fkey" FOREIGN KEY (filter_type) REFERENCES conferati.filtertypes_st(type) not valid;

alter table "filters"."app_whitefilter_st" validate constraint "app_whitefilter_st_filter_type_fkey";

alter table "filters"."record_section_blackfilter_st" add constraint "record_section_blackfilter_st_filter_type_fkey" FOREIGN KEY (filter_type) REFERENCES conferati.filtertypes_st(type) not valid;

alter table "filters"."record_section_blackfilter_st" validate constraint "record_section_blackfilter_st_filter_type_fkey";

alter table "filters"."record_section_whitefilter_st" add constraint "record_section_whitefilter_st_filter_type_fkey" FOREIGN KEY (filter_type) REFERENCES conferati.filtertypes_st(type) not valid;

alter table "filters"."record_section_whitefilter_st" validate constraint "record_section_whitefilter_st_filter_type_fkey";


create table "public"."testtable" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "name" text
);


alter table "public"."testtable" enable row level security;

CREATE UNIQUE INDEX testtable_pkey ON public.testtable USING btree (id);

alter table "public"."testtable" add constraint "testtable_pkey" PRIMARY KEY using index "testtable_pkey";


